// scripts/build-blog.js
// Reads src/content/blog/*.md and writes src/content/generated-posts.ts.
// Keeps markdown parsing (gray-matter/marked) out of the app's client bundle —
// the app only ever imports the plain generated data.
import matter from 'gray-matter';
import { marked } from 'marked';
import fs from 'fs';
import path from 'path';

const BLOG_DIR = './src/content/blog';
const OUT_FILE = './src/content/generated-posts.ts';

function estimateReadingTime(text) {
  const words = text.trim().split(/\s+/).length;
  return Math.max(1, Math.ceil(words / 200));
}

function buildPosts() {
  return fs
    .readdirSync(BLOG_DIR)
    .filter((file) => file.endsWith('.md') && file.toLowerCase() !== 'readme.md')
    .map((file) => {
      const raw = fs.readFileSync(path.join(BLOG_DIR, file), 'utf-8');
      const { data, content } = matter(raw);
      return {
        slug: file.replace(/\.md$/, ''),
        title: data.title,
        excerpt: data.excerpt,
        category: data.category,
        date: data.date,
        readingTime: estimateReadingTime(content),
        html: marked.parse(content, { async: false }),
      };
    })
    .sort((a, b) => (a.date < b.date ? 1 : -1));
}

function writeGeneratedFile(posts) {
  const header = `// AUTO-GENERATED by scripts/build-blog.js from src/content/blog/*.md — do not edit by hand.\n\nexport interface GeneratedPost {\n  slug: string;\n  title: string;\n  excerpt: string;\n  category: string;\n  date: string;\n  readingTime: number;\n  html: string;\n}\n\nexport const posts: GeneratedPost[] = `;
  const body = JSON.stringify(posts, null, 2);
  fs.writeFileSync(OUT_FILE, `${header}${body};\n`);
}

writeGeneratedFile(buildPosts());
